; Omote OS — OMOTE Rev 1-4 (ESP32)
[platformio]
default_envs = omote-rev4
src_dir = src

[env]
platform = espressif32@6.8.1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board = esp32dev
board_build.f_flash = 80000000L
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
lib_deps =
	lvgl/lvgl@^8.3.11
	lovyan03/LovyanGFX@^1.2.0
	crankyoldgit/IRremoteESP8266@^2.8.6
	h2zero/NimBLE-Arduino@^1.4.3
	bblanchon/ArduinoJson@^7.2.0
	sparkfun/SparkFun LIS3DH Arduino Library
	sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library
	bitbank2/PNGdec@^1.1.0
	links2004/WebSockets@^2.4.1
build_flags =
	-D OMOTE_HARDWARE_REV=4
	-D SCR_WIDTH=240
	-D SCR_HEIGHT=320
	-D LV_CONF_SKIP=1
	-D LV_TICK_CUSTOM=1
	-D LV_MEM_CUSTOM=0
	-D LV_MEM_SIZE="(36U * 1024U)"
	-D CONFIG_ARDUINO_LOOP_STACK_SIZE=12288
	-D LV_FONT_MONTSERRAT_12=1
	-D LV_FONT_MONTSERRAT_14=1
	-D LV_FONT_MONTSERRAT_16=0
	-D LV_FONT_MONTSERRAT_24=0
	-D LV_THEME_DEFAULT_DARK=1
	-D LV_BUILD_EXAMPLES=0
	-D LV_USE_LOG=0
	-D SPI_FREQUENCY=40000000
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
	-D WEBSOCKETS_MAX_DATA_SIZE=2048
	-D CONFIG_BT_ENABLED=1
	-D CONFIG_BT_NIMBLE_MAX_BONDS=3
	-D CONFIG_BT_NIMBLE_MAX_CCCDS=12
	-I src
extra_scripts = pre:extra_script.py

[env:omote-rev4]
extends = env
build_flags =
	${env.build_flags}
	-D OMOTE_HA_REST_ONLY=1
	-Os
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
